# Generated by Django 5.1.6 on 2025-02-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
        migrations.AddField(
            model_name='entry',
            name='Entry',
            field=models.TextField(blank=True, default='محتوا هنوز اضافه نشده است.', help_text='متن کامل مقاله را اینجا بنویسید.', null=True, verbose_name='محتوای مقاله'),
        ),
    ]
