# Generated by Django 5.1.6 on 2025-02-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0003_remove_entry_text_entry_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Entry',
            new_name='text',
        ),
    ]
