# Generated by Django 5.1.6 on 2025-02-18 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0004_rename_entry_entry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSMModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(help_text='IMEI منحصر\u200cبه\u200cفرد ماژول را وارد کنید.', max_length=15, unique=True, verbose_name='IMEI دستگاه')),
                ('operator', models.CharField(help_text='نام اپراتور سیم\u200cکارت در ماژول.', max_length=50, verbose_name='نام اپراتور')),
                ('signal_strength', models.IntegerField(help_text='قدرت سیگنال بر اساس dBm.', verbose_name='قدرت سیگنال (dBm)')),
                ('status', models.BooleanField(default=True, help_text='فعال/غیرفعال بودن ماژول GSM.', verbose_name='وضعیت فعال بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'ماژول GSM',
                'verbose_name_plural': 'ماژول\u200cهای GSM',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(blank=True, default='محتوا هنوز اضافه نشده است', help_text='متن کامل مقاله را اینجا بنویسید', null=True, verbose_name='محتوای مقاله'),
        ),
        migrations.CreateModel(
            name='OutgoingSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(help_text='شماره تلفنی که پیامک به آن ارسال شده است.', max_length=20, verbose_name='شماره گیرنده')),
                ('message', models.TextField(help_text='محتوای پیامک ارسالی.', verbose_name='متن پیامک')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('gsm_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='webchat.gsmmodule', verbose_name='ماژول GSM مرتبط')),
            ],
            options={
                'verbose_name': 'پیامک ارسالی',
                'verbose_name_plural': 'پیامک\u200cهای ارسالی',
            },
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='شماره تلفنی که پیامک ارسال کرده است.', max_length=20, verbose_name='شماره فرستنده')),
                ('message', models.TextField(help_text='محتوای پیامک دریافتی یا ارسالی.', verbose_name='متن پیامک')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دریافت')),
                ('gsm_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='webchat.gsmmodule', verbose_name='ماژول GSM مرتبط')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
            },
        ),
    ]
