# Generated by Django 5.1.6 on 2025-02-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0007_alter_author_options_alter_book_options_book_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AddField(
            model_name='entry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
