# Generated by Django 5.1.6 on 2025-02-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0008_alter_topic_options_entry_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'عنوان خبر',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.CreateModel(
            name='News_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webchat.news')),
            ],
            options={
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
