# Generated by Django 5.1.6 on 2025-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0009_news_alter_entry_file_news_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ماشین را وارد کنید', max_length=100)),
                ('color', models.CharField(choices=[('red', 'قرمز'), ('green', 'سبز'), ('blue', 'آبی'), ('black', 'مشکی'), ('white', 'سفید')], help_text='رنگ ماشین را انتخاب کنید', max_length=10)),
                ('model_year', models.IntegerField(help_text='سال ساخت ماشین را وارد کنید')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
