# Generated by Django 5.1.6 on 2025-02-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0011_alter_book_author_alter_entry_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_at',
        ),
    ]
