# Generated by Django 5.1.6 on 2025-02-25 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0013_entry_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.RemoveField(
            model_name='news_report',
            name='news',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان خبر')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField(verbose_name='متن خبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='تصویر خبر')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده؟')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='webchat.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_date'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='News_report',
        ),
    ]
