# Generated by Django 4.2.19 on 2025-03-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0015_alter_article_options_answer_question_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
